guess-fix for test failure on GH actions
  As2::Message::#valid_signature?#test_0003_is false when signature does not match content:
  ArgumentError: wrong number of arguments (given 1, expected 2..3)
      /home/runner/work/as2/as2/test/message_test.rb:40:in `decrypt'
      /home/runner/work/as2/as2/test/message_test.rb:40:in `block (3 levels) in <top (required)>'

https://github.com/andjosh/as2/runs/4675196664

happens on ruby 2.5 and 2.7. passes locally, so perhaps OSX vs linux issue?